language: go

env:
  global:
    - secure: eNsN0KUpsJvRdBe9W4vaVRt6rSVmbJg/8uBQE15DOJ5ubURaG0t+xx77VDc0ScT9Jb7PwPePr1nS37ZbYbfrXqvdnHPTFTEte8jXERU1DN5xHpKw9aOmhYn/TrXcpVMh98v/GcbRFpQONbdum1CJFyApVD2n16TKZlg7pi+iYkE7XalpLCkQhEQPWkP/q/wPiUT3uBTrARGobRDl+aqQJCxsKDMgtsIBLHQuPffc3WesbykNeNRJklF4Prgfu/EyWDU/1MWKv2M6sqrNfSj0FpfDCDJl80DvatGYFyasweZ2VPqwnfBl4Vi3PXVqBVft1afsn0Ue0QNpZ0ssiEXMLHNajLMTyobF0nr9ScKeTtxtDMCaP3oYQ5CVNiAtWM2jLKC5/qFvCGDJZIxNDyonfhgYcbjoiq1AphTUQoBe30MYZzNvkvcUi69DgPxyYDNroApCjpLeMGPQccw8UhVy/9bnPEHOQ++xBM8ERFDO29qHEDwjs1box8B/n1FeNTKnp+uPieJ9XD5tn6T+07iK2uqJK3o+krIaDOXuatntfR2DfyvOfpaOGu0mRvkpfwM9gJsv4Gz507xfwZKSM1sRaFDX2N6nnVEFTxIdtZzaAYjQhW4K8m/0KImTmSkAF0VXw0+9LvJMNnaIragSTvWp90Yhww4cURo8fURvJKKm2x4=
    - secure: sW7wg+mZoOZ49oj6TQMHwsSJKJA0gYJUT3jDwBHNiS/rh7HNx7t9z5BslnfLBWzaAYi70j9oROdQ6cg19hQzurK7ZFkkGxnTMhc5XkSGe0lZnzlFXb38KjW/dUzpREsr1T2Yfjf5yWcMiySN6RPyl6OTIGKK6Xhaxr25C3u3o/AgYF5BVRPZZH10HOOsGZb8cqMuNII3v5YTW1Kgnw+5Vf7Rh0asClTv3y6DPNeURjCctZEWuC1Zf/1YtA/VgQO7SVKJlTkDvSUHmt3jsWdzPP6x4xpOixmBCmXR/tPIhpaiTa2pawZUcPbZeTk8exAE1jdL+tUfQVJH15j3bjb/gplj5ZXf8zqCWA4WXkVFUbNdAfQ8vnviFxBB7PGoXIMlVSF3KsHig7BhUN55qfjnT7Nxu0BharFN3I+ZmoHrZTi4cWdayiZQFvOGCalkUkB3fpm+aS4QNS8Rj3OgtKrN6jE4nCd7+t+BjvQadcSzsZsXME+13Bnpv9KQX4eLxJoZdWscpjyIBLbusEnKrlRAf8MnZTzlgJxzQE2hf/rbQYJjsXrS5u9SaogjJj1i1C+eVd5/HdGxnOvFdIEA+aCxQGf3rm9VIKjxPrHUeblUxYpHZAF/hKpW7QKKzCpDns/60PsU5S6c5aHh8plCj/LMgFHF7rdOziWn9x3iaCSetw4=

before_install:
  - gem install asciidoctor

install:
  - go get -v github.com/spf13/hugo

script:
  - git clone https://github.com/jbub/ghostwriter ./themes/ghostwriter
  - hugo

after_success:
  "curl --ftp-create-dirs -T config.toml -u $FTPUSR:$FTPPWD ftp://w0077e1b.kasserver.com:21/www/test/config.toml"
