language: go

secure:
  - "eNsN0KUpsJvRdBe9W4vaVRt6rSVmbJg/8uBQE15DOJ5ubURaG0t+xx77VDc0ScT9Jb7PwPePr1nS37ZbYbfrXqvdnHPTFTEte8jXERU1DN5xHpKw9aOmhYn/TrXcpVMh98v/GcbRFpQONbdum1CJFyApVD2n16TKZlg7pi+iYkE7XalpLCkQhEQPWkP/q/wPiUT3uBTrARGobRDl+aqQJCxsKDMgtsIBLHQuPffc3WesbykNeNRJklF4Prgfu/EyWDU/1MWKv2M6sqrNfSj0FpfDCDJl80DvatGYFyasweZ2VPqwnfBl4Vi3PXVqBVft1afsn0Ue0QNpZ0ssiEXMLHNajLMTyobF0nr9ScKeTtxtDMCaP3oYQ5CVNiAtWM2jLKC5/qFvCGDJZIxNDyonfhgYcbjoiq1AphTUQoBe30MYZzNvkvcUi69DgPxyYDNroApCjpLeMGPQccw8UhVy/9bnPEHOQ++xBM8ERFDO29qHEDwjs1box8B/n1FeNTKnp+uPieJ9XD5tn6T+07iK2uqJK3o+krIaDOXuatntfR2DfyvOfpaOGu0mRvkpfwM9gJsv4Gz507xfwZKSM1sRaFDX2N6nnVEFTxIdtZzaAYjQhW4K8m/0KImTmSkAF0VXw0+9LvJMNnaIragSTvWp90Yhww4cURo8fURvJKKm2x4="

before_install:
  - gem install asciidoctor

install:
  - go get -v github.com/spf13/hugo

script:
  - git clone https://github.com/jbub/ghostwriter ./themes/ghostwriter
  - hugo

after_success:
  - find public -type f -exec curl -u w0077e1b:$FTPPWD --ftp-create-dirs -T {} ftp://w0077e1b.kasserver.com/www/test/{} \;