languageCode = "en-us"
title = "www.mirkosertic.de"
theme= "ghostwriter"
baseurl = "https://test.mirkosertic.de"
copyright = "Mirko Sertic"
googleAnalytics = "UA-33614060-2"
disqusShortname = "www-mirkosertic-de"
canonifyURLs = true

[Taxonomies]
    tag = "tags"

[Author]
    name = "Mirko Sertic"

[Params]
    intro = true
    headline = "Welcome to the Blog of Mirko Sertic"
    description = "The personal Blog of a software engineer"
    github = "https://github.com/mirkosertic"
    linkedin = "https://de.linkedin.com/in/mirko-sertic-98882397"
    gplus = "https://plus.google.com/112732493059943659026"
    twitter = "https://twitter.com/mirkosertic"
    email = "mirko@mirkosertic.de"
    opengraph = true
    shareTwitter = true

[Permalinks]
    post = "blog/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1